apiVersion: v1
kind: Service
metadata:
  name: styleclip-backend-service
spec:
  selector:
    app: styleclip-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
